language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm

env:
- TEST_DOMAIN=localhost:8080

before_script:
  - sudo ./tests/data/setup_nginx_for_travis.sh

script: phpunit tests/
