language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm
    - php: nightly
    - php: hhvm-nightly

before_script:
  - sudo ./tests/data/setup_nginx_for_travis.sh
  - composer self-update
  - composer install

script: phpunit tests/
